### ISSUE TITLE
Adding some food cards after the carousel to improve the UI

### ISSUE THREAD

**Issue by Adarsh-k0802** [flyingSaucer87/community-website#107]
I feel like homepage needs some changes.

**Comment by Adarsh-k0802** [comment]
@flyingSaucer87 can i work on this ?

**Comment by flyingSaucer87** [comment]
Sure. @Adarsh-k0802 go ahead with the issue.

**Comment by SabujGolui** [comment]
Assign it to me. I'll be more than pleased to assist.

**Comment by Adarsh-k0802** [comment]
> Sure. @Adarsh-k0802 go ahead with the issue.

done
