### ISSUE TITLE
Several Alignment Issues

### ISSUE THREAD

**Issue by KislayMishra69** [flyingSaucer87/community-website#114]
There are several alignment issues in the landing page which need changes.
![image](https://user-images.githubusercontent.com/78745590/194559699-8276abde-2836-4a7a-94a3-3a565f418fa5.png)

Also the website looks terrible in the mobile
![image](https://user-images.githubusercontent.com/78745590/194559902-b6b66345-e17a-49ad-8977-09bc7d4f9179.png)

**Comment by najeebkp** [comment]
hi @KislayMishra69 please assign this to me

**Comment by flyingSaucer87** [comment]
Sure @najeebkp. You can go ahead with the fixes. The issue has been assigned to you
