### ISSUE TITLE
About section contains some duplicate sections.

### ISSUE THREAD

**Issue by nihshesh** [flyingSaucer87/community-website#131]
![image](https://user-images.githubusercontent.com/61341935/194689964-c2a99119-2c79-4dd1-9045-3e03f3ff132b.png)

**Comment by nihshesh** [comment]
Please assign me this issue

**Comment by flyingSaucer87** [comment]
Please do the needful changes @nihshesh. You have been assigned this issue.

**Comment by JatinSingh08** [comment]
Hey @flyingSaucer87  assign this issue to me please
