### ISSUE TITLE
Images are not loading 

### ISSUE THREAD

**Issue by Agrimaagrawal** [flyingSaucer87/community-website#134]
These images are not loading ,I can solve this issue ,please assign me this  issue under hacktoberfest 
![Presentation1](https://user-images.githubusercontent.com/84567933/194694199-b7b134fe-504c-4ea7-9b75-70be9440b1b0.jpg)

**Comment by flyingSaucer87** [comment]
Please do the needful @Agrimaagrawal

**Comment by Agrimaagrawal** [comment]
ok I wiil do this
