### ISSUE TITLE
Wrong phone Icon

### ISSUE THREAD

**Issue by Anthonyushie** [flyingSaucer87/community-website#136]
The telephone icon is wrong, please assign me to this issue under hacktoberfest
![Screenshot (128)_LI](https://user-images.githubusercontent.com/66975592/194700114-11b6af2a-e50c-40b0-9d6b-2d2b9d01375d.jpg)

**Comment by flyingSaucer87** [comment]
Sure! Please do the required changes @Anthonyushie
