### ISSUE TITLE
Contact form alignment issue

### ISSUE THREAD

**Issue by KislayMishra69** [flyingSaucer87/community-website#138]
The contact form is not aligned properly. It could have some changes.
![image](https://user-images.githubusercontent.com/78745590/194704324-68953431-04f5-4c0a-8d1f-62c965a0cd07.png)

**Comment by satyamrs00** [comment]
I am doing this one 
Assign it to me

**Comment by flyingSaucer87** [comment]
@satyamrs00 Please do the required changes. Good luck
