### ISSUE TITLE
Change the text styles

### ISSUE THREAD

**Issue by flyingSaucer87** [flyingSaucer87/community-website#14]
The font of the project is looking really small and blunt. Some changes will be really appreciated

**Comment by KaustubhMishra69** [comment]
I can work on this issue. Please assign it to me and I will get to work!

**Comment by keshav-rockwinder** [comment]
i want to solve this issue can you please assign me this task

**Comment by flyingSaucer87** [comment]
@keshav-rockwinder This issue has been closed
