### ISSUE TITLE
Contact us section has duplicate texts

### ISSUE THREAD

**Issue by poojasanwal** [flyingSaucer87/community-website#152]
The contact us section has the same content written twice. Moreover, there are unnecessary spaces in the content. Please assign me this issue so I can fix this. Thanks!

1)

<img width="1416" alt="Screenshot 2022-10-09 at 7 48 09 AM" src="https://user-images.githubusercontent.com/71871670/194737758-72b2dbcf-4fb1-4514-9b71-19db44c7c968.png">

2)

<img width="1411" alt="Screenshot 2022-10-09 at 7 48 36 AM" src="https://user-images.githubusercontent.com/71871670/194737768-20184921-3747-46ae-bb74-447249002e7c.png">

**Comment by flyingSaucer87** [comment]
Sure. You can go ahead with the required changes. I have assigned this issue to you @poojasanwal

**Comment by poojasanwal** [comment]
Thank you so much! I will get started (: @flyingSaucer87

**Comment by Anish-Parkhi** [comment]
I would like to work on this issue 
I will make sure to resolve this issue and make PR in very less time

**Comment by poojasanwal** [comment]
This issue has been fixed by someone else. So, i would like to go for another one. Thanks!
