### ISSUE TITLE
Redesigning the logo of the website 

### ISSUE THREAD

**Issue by Pushkar03** [flyingSaucer87/community-website#153]
I can provide a good logo for the website as the current one is quite outdated.

**Comment by flyingSaucer87** [comment]
Please do! We can use a new logo. This issue is assigned to you @Pushkar03

**Comment by Pushkar03** [comment]
###  **Logo for Los Pollos Hermanos**

![Logo for Los Pollos Hermanos](https://user-images.githubusercontent.com/81770626/194763268-1fc4afca-1530-4f78-aeef-f5375da41262.png)

![Logo](https://user-images.githubusercontent.com/81770626/194763407-27a595b0-4361-42ca-b661-ba5d69dbb645.png)

![Logo(1)](https://user-images.githubusercontent.com/81770626/194763481-abb3e068-9f77-4dab-a1c5-898f09c8493b.png)

**Comment by flyingSaucer87** [comment]
@Pushkar03 The logo looks really amazing. But in order to get it counted for Hacktoberfest, please go to the folder 'Los pollos Hermanos_files' and add the logo from there. It will create a PR.

**Comment by Pushkar03** [comment]
@flyingSaucer87 thank you firstly, I have added the logo in the folder and made a PR. Kindly merge!
