### ISSUE TITLE
Fix About Us Page

### ISSUE THREAD

**Issue by Ayush-Khandelwal28** [flyingSaucer87/community-website#159]
I feel like (Aboutus.html and Aboutus.css) needs some changes, they do not look aligned with the Home and Contact Us page.

I would like to fix the issue.
Please assign the issue to me, and add the Hacktoberfest Label.

**Comment by flyingSaucer87** [comment]
Sure. Please go ahad with the changes. This issue has been assigned to you @Ayush-Khandelwal28

**Comment by Ayush-Khandelwal28** [comment]
I have fixed the Navbar of the About Us page.

BEFORE

![image](https://user-images.githubusercontent.com/97888676/194759382-e631eb38-2f12-45cb-a9af-6e098baccbc3.png)


NOW

![image](https://user-images.githubusercontent.com/97888676/194759400-383eebcb-6192-46d4-8718-47e6bd288680.png)


Now, it is in sync with the overall website.
