### ISSUE TITLE
Change the Los Pollos Logo

### ISSUE THREAD

**Issue by KislayMishra69** [flyingSaucer87/community-website#168]
A new logo has been added for the company in the folder 'Los Pollos Hermanos_files', which has been made by one of our own contributors. Considering this is a community-built website, it'd only be fair if we replace the current logo with the new logo.

**Comment by priyanshu6781** [comment]
Hey, I would like to work. Could you please assign this to me!!

**Comment by jsvigneshkanna** [comment]
assign to my name please

**Comment by jsvigneshkanna** [comment]
Hi @flyingSaucer87 ,
have raised new PR for this issue: #170
