### ISSUE TITLE
Update the about us section

### ISSUE THREAD

**Issue by satyam73** [flyingSaucer87/community-website#169]
I feel like (FILE NAME) needs some changes.
I want to update the about us section and make it more responsive and user-friendly. Please assign me this issue so that I can work on this improvisation.
![image](https://user-images.githubusercontent.com/85296770/194766121-ed7915ce-fd98-46e0-b4cb-844d01433462.png)

**Comment by flyingSaucer87** [comment]
Hey @satyam73. Please give a little more details about what changes you wish to make

**Comment by satyam73** [comment]
Yes sure, I am mentioning some points which are in my mind here as follows:

- Firstly I will kind of make it look separate from the other section by adding a separator or maybe by adding a suitable background to it so it kind of gets a separate look.
- Then both the images and paragraph are aligned in a stacked row for which the user first sees the image and then scrolls to view its content. I will make it look like that image will be aligned left and the content will be shown to its right with the proper heading.
- Will also add a menu call to action button of this section to a certain position so it will become more appealing and easy to find for the user.

Let me know what you think of this.
Thanks!

**Comment by flyingSaucer87** [comment]
@satyam73 Sounds good! Please go ahead with your desired changes. Good luck
