### ISSUE TITLE
Build a menu.html

### ISSUE THREAD

**Issue by flyingSaucer87** [flyingSaucer87/community-website#17]
Build a html page for the menu of the restaurant. and link it to the menu button in main.html

**Comment by vkilng** [comment]
I'd like to work on this. Please assign this to me!

**Comment by flyingSaucer87** [comment]
Go ahead with it @vkilng! Really appreciate your contributions

**Comment by keshav-rockwinder** [comment]
i would like to contribute to this project? please create a pull request for me @flyingSaucer87

**Comment by flyingSaucer87** [comment]
@keshav-rockwinder This issue has already been assigned to @vkilng. But stick around coz we'll be adding some more issues to the repo!!

**Comment by vkilng** [comment]
I see that @keshav-rockwinder has contributed by creating menu.html
Kudos! @flyingSaucer87 you may close this issue!
