### ISSUE TITLE
Wrong positioning in about page

### ISSUE THREAD

**Issue by Anthonyushie** [flyingSaucer87/community-website#172]
wrong positioning in about page, please assign me to this isssue under hacktoberfest
![Screenshot (134)_LI](https://user-images.githubusercontent.com/66975592/194775197-c7311011-e8d7-436a-8363-52421f720f82.jpg)

**Comment by diksha0149** [comment]
Hi @flyingSaucer87 , Please assign me this issue. I am good in frontend, you can checkout my projects (Link : [https://diksha0149.github.io/Portfolio/](https://diksha0149.github.io/Portfolio/) and [https://ietdavv.acm.org/](https://ietdavv.acm.org/) )
Thank you.

**Comment by Anish-Parkhi** [comment]
I would like to work on this issue
