### ISSUE TITLE
Button Text Spacing on Landing Page's Featured Items

### ISSUE THREAD

**Issue by marisabrantley** [flyingSaucer87/community-website#175]
I feel like style.css needs some changes.

A small issue, but the text line spacing on the landing page's "Order Now" buttons needs attention. I'd like to fix it!

<img width="1150" alt="Screen Shot 2022-10-09 at 5 09 25 PM" src="https://user-images.githubusercontent.com/60168324/194786176-fc0e51b4-0573-4769-9150-fb979b2ae26e.png">

**Comment by flyingSaucer87** [comment]
Sure @marisabrantley. I have assigned this issue to you. Please go ahead with the changes

**Comment by marisabrantley** [comment]
Thank you!

**Comment by shivam7242** [comment]
sir, can I work on that issue? I think I can do CSS in a much better way
