### ISSUE TITLE
small subscribe input 

### ISSUE THREAD

**Issue by gasaroleila** [flyingSaucer87/community-website#181]
The input is smaller than the button; emails won't fit in the input. please assign this to me under hacktoberfest2022
![Screenshot (358)](https://user-images.githubusercontent.com/61538202/194839299-7466ac97-259f-4bec-941a-e1894074d353.png)

**Comment by flyingSaucer87** [comment]
Please do the needful changes @gasaroleila

**Comment by gasaroleila** [comment]
> Please do the needful changes @gasaroleila

sure
