### ISSUE TITLE
The design of menu button needs fixing.

### ISSUE THREAD

**Issue by nihshesh** [flyingSaucer87/community-website#184]
While hovering over Menu button the background colour of it is getting mixed with the body background.
![image](https://user-images.githubusercontent.com/61341935/194844716-e42107c9-c559-4370-b24f-740f5ab1e624.png)

**Comment by nihshesh** [comment]
Please assign me this issue so I can start working.

**Comment by flyingSaucer87** [comment]
Sure @nihshesh. Please go ahead with this issue

**Comment by Akash7649** [comment]
please assign me this issue
