### ISSUE TITLE
Clicking on logo on navbar takes you to home

### ISSUE THREAD

**Issue by sidharthbh8** [flyingSaucer87/community-website#186]
![navbar](https://user-images.githubusercontent.com/92387052/194852288-6cbef019-6e9d-4168-b961-c84d59059a67.PNG)
I just observed that by clicking on the logo of the page in the navbar when we are on any other page nothing happens I can change it to make it land on the Home page.

**Comment by sidharthbh8** [comment]
@flyingSaucer87  Kindly assign me this issue.

**Comment by flyingSaucer87** [comment]
Sure. Go ahead with the issue @sidharthbh8
