### ISSUE TITLE
Quick links needs to be centered.

### ISSUE THREAD

**Issue by Wutche** [flyingSaucer87/community-website#187]
Quick links need to be centered, please assign me to this issue under hacktober fest.
![Screenshot 2022-10-10 115846](https://user-images.githubusercontent.com/93476943/194851952-42534241-1343-42ea-b85e-1310484aa792.png)

**Comment by flyingSaucer87** [comment]
Sure @Techguy04. Please go ahead with the changes. I have assigned this issue to you.
