### ISSUE TITLE
Footer links font color

### ISSUE THREAD

**Issue by jsvigneshkanna** [flyingSaucer87/community-website#189]
Footer links font color should be changed to black or other contrast color to background as it difficult to find the links

Please assign me this issue

**Comment by flyingSaucer87** [comment]
Sure @jsvigneshkanna. Please go ahead with the changes

**Comment by hm05** [comment]
Hello @flyingSaucer87 I am a college first year student and I don't have much knowledge. But this is a task which I think I can try. So I would be glad if you assign me this project

**Comment by Akash7649** [comment]
pleas assign me this issue

**Comment by Akash7649** [comment]
please assign me this issue
