### ISSUE TITLE
Wrong positioning in Newsletter section

### ISSUE THREAD

**Issue by Wutche** [flyingSaucer87/community-website#196]
wrong positioning in newsletter section. Please assign me to this issue under hacktober fest.
![news letter](https://user-images.githubusercontent.com/93476943/194897734-f8cfcd21-7c2d-44ac-9946-afe03ee5cbae.png)

**Comment by flyingSaucer87** [comment]
It looks good as it is to me. Can you please explain what changes you wish to do?

**Comment by Wutche** [comment]
Uhm in terms of animation it's not displaying properly is goes off and on

**Comment by flyingSaucer87** [comment]
I don't feel like it needs any improvement. Please wait for the next issue to be raised for contributing!
