### ISSUE TITLE
Issue with responsiveness

### ISSUE THREAD

**Issue by subhajitroycode** [flyingSaucer87/community-website#205]
![image](https://user-images.githubusercontent.com/72935263/195033475-444ed1aa-d12f-4119-ae15-843997bd5dff.png)

Hi there, I found out that this website isn't very responsive at all. So if you assign me this I make this website responsive for most screens possible.

**Comment by flyingSaucer87** [comment]
This seems like a major issue. @subhajitroycode please go ahead with it. I have assigned this issue to you!

**Comment by subhajitroycode** [comment]
Yeah it's a major issue so it's gonna take a little bit of a time
