### ISSUE TITLE
Issue with Text Color

### ISSUE THREAD

**Issue by Wutche** [flyingSaucer87/community-website#212]
Text Color is wrong, please assign me to this issue under hacktoberfest
![Screenshot 2022-10-11 144432](https://user-images.githubusercontent.com/93476943/195113481-527432e7-6aa6-4d79-a29a-1223121823f7.png)

**Comment by flyingSaucer87** [comment]
I don't feel like it needs any change. Please suggest some valuable changs instead of such spammy issues to work on
