### ISSUE TITLE
Change logos in about us and contact pages

### ISSUE THREAD

**Issue by KislayMishra69** [flyingSaucer87/community-website#213]
The logo should be changes on about and contact pages as well. Currently it is only up for the landing page.

The Logo on the main page:

![image](https://user-images.githubusercontent.com/78745590/195156661-e66dfd7f-0f3d-46c6-9ee2-f8565da852ae.png)

The logo on the about us and contact pages:

![image](https://user-images.githubusercontent.com/78745590/195156790-369839f6-4332-40c6-95da-9121eff43b2e.png)

**Comment by jsvigneshkanna** [comment]
@flyingSaucer87 , can you please assign this issue to my name, will fix
