### ISSUE TITLE
Need a footer for the website

### ISSUE THREAD

**Issue by flyingSaucer87** [flyingSaucer87/community-website#22]
Let's create a simple footer for the website. An example is provided:
![image](https://user-images.githubusercontent.com/113417364/193416184-e5ddd2f4-7687-4aae-93dd-a6aaee2a1f35.png)

**Comment by ahmedsilat44** [comment]
Hey @flyingSaucer87 I would like to do this task. Could you assign it to me. Thanks 😄

**Comment by sunidhisachan** [comment]
hey @flyingSaucer87 , I can try this.

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey man, I would like to work on this. Could you assign it to me please. Thank you

**Comment by Sarabjeet108** [comment]
Would like to work on this issue. Can you assign it to me?

**Comment by HimangsKalita** [comment]
could you check this Added footer and fixed some errors in css #24

**Comment by Dhruvpandey08** [comment]
Hi I have created a PR #25 for this issue kindly review and accept the PR.

**Comment by flyingSaucer87** [comment]
@ABHIGYAN-MOHANTA This issue has been assigned to you. Good luck!

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey man, now since footer is already added, I think you can close this. Although if you need any more changes like adding your company name to the footer. Just drop a messege and I can do it. Sorry for being late.

**Comment by flyingSaucer87** [comment]
@ABHIGYAN-MOHANTA You can go ahead with the changes you wish to do. I will review them.

**Comment by ABHIGYAN-MOHANTA** [comment]
For now there nothing much I can do that will greatly change the footer, but I can make a few subtle changes. Although I would say, the footer is great as it is. I will be making a pr shortly, you can discard it if you want. And thanks for the oppurtunity.

**Comment by ABHIGYAN-MOHANTA** [comment]
Nah man, any changes is just too much. The footer is actually great and in the sweet spot. You can close this issue. Thanks!
