### ISSUE TITLE
BackToTop button

### ISSUE THREAD

**Issue by sidharthbh8** [flyingSaucer87/community-website#220]
![backtotop](https://user-images.githubusercontent.com/92387052/195190302-28728501-d787-44ce-9fab-3680a78cb6b2.png)
realign the Back to top button and make it more stylish
assign me this issue. @flyingSaucer87

**Comment by flyingSaucer87** [comment]
sure @sidharthbh8. Go ahead with the issue

**Comment by itsOmSarraf** [comment]
Rectified , please check the PR.
