### ISSUE TITLE
improve why choose us section in about page

### ISSUE THREAD

**Issue by satyam73** [flyingSaucer87/community-website#222]
Hello there,
While I am scrolling through the website I saw that I can improve the "why choose us" section on the about us page. Please assign me this issue so that I can work on the same.
Attaching the image for reference.
![image](https://user-images.githubusercontent.com/85296770/195299454-c048db0e-6c8e-4da8-ac91-ddb7805f993b.png)

Thanks!

**Comment by flyingSaucer87** [comment]
Sure @satyam73. Please do the needful changes

**Comment by satyam73** [comment]
This issue is done in #247 closing the issue.
