### ISSUE TITLE
The about-us section has repetitive content.

### ISSUE THREAD

**Issue by poojasanwal** [flyingSaucer87/community-website#227]
The content in the "About us" section is repetitive. The navbar and carousel appears within the about section when it is not needed. Please assign me this issue so I can begin working on it. Thanks!

<img width="1440" alt="Screenshot 2022-10-12 at 9 27 11 PM" src="https://user-images.githubusercontent.com/71871670/195511791-9c44585d-3de5-40ec-8674-60788649bdd3.png">

Moreover, the home content pictures appear in the about section. 

<img width="595" alt="Screenshot 2022-10-12 at 9 26 41 PM" src="https://user-images.githubusercontent.com/71871670/195511820-dffbf730-9257-42b6-83e3-d85bae7bca58.png">

Other than this, the about content itself is being repeated.

**Comment by flyingSaucer87** [comment]
Please go ahead with the changes @poojasanwal
