### ISSUE TITLE
Newletter subscription button does not check for email validity.

### ISSUE THREAD

**Issue by poojasanwal** [flyingSaucer87/community-website#228]
The newsletter email field does not check for email validity. If you kindly assign me this issue, I'd like to fix the same. Thank you!

<img width="685" alt="Screenshot 2022-10-13 at 11 33 56 AM" src="https://user-images.githubusercontent.com/71871670/195516285-052338ee-611c-4620-926c-b65b55a11ad6.png">

**Comment by flyingSaucer87** [comment]
sure @poojasanwal. Please go ahead with the changes
