### ISSUE TITLE
Buttons didn't look good

### ISSUE THREAD

**Issue by itsOmSarraf** [flyingSaucer87/community-website#244]
# before 

![image](https://user-images.githubusercontent.com/83817663/195914837-ba71daa2-7610-4c1f-a890-6b56d1ece569.png)

# after 

![image](https://user-images.githubusercontent.com/83817663/195914915-851d59c5-072d-4733-a656-d203478c11b2.png)

P.s. do add hacktoberfest before merging it :)

**Comment by ranaji038** [comment]
@itsOmSarraf  Please Assign me this issue

**Comment by itsOmSarraf** [comment]
Hey @ranaji038 I have already raised a PR, and I am not a maintainer , so can't assign it to you :)
