### ISSUE TITLE
About us Section becomes too messy when resolution changed  

### ISSUE THREAD

**Issue by soham1826** [flyingSaucer87/community-website#250]
I feel like about us section on home page needs some changes
@flyingSaucer87  please assign me this issue under hactoberfest i will solve it immediately
![image](https://user-images.githubusercontent.com/107259970/196214918-3409a2b2-7d73-4f55-b7b6-325c85f83606.png)

**Comment by flyingSaucer87** [comment]
sure @soham1826. Please do all the needful changes

**Comment by soham1826** [comment]
hey  @flyingSaucer87  i think the about us section and its content  in our home page is Repeated 3 times  should i delete the extra ones and adjust so that it will look nice or do you have any other suggession

 1.first image is from starting of home page where already about us section is
<img width="860" alt="repo 2" src="https://user-images.githubusercontent.com/107259970/196340093-34cee7c1-d62c-4fc1-8213-a3c2a88cb1ab.png">

2. and second is repeated code and content of about us after scrolling down

<img width="1220" alt="repo" src="https://user-images.githubusercontent.com/107259970/196340215-24311236-9844-444b-a65b-757191a3481d.png">

**Comment by soham1826** [comment]
i think the later section is supposed to be a Contact us section before Footer

**Comment by soham1826** [comment]
![image](https://user-images.githubusercontent.com/107259970/196348575-99237c97-a192-42a4-9a38-c284528fa275.png)
I made it something like this
