### ISSUE TITLE
the navigation of contact link in about us is not working(whereas the home link is working)

### ISSUE THREAD

**Issue by Akshitha2106** [flyingSaucer87/community-website#256]
Respected sir (@flyingSaucer87 ) please assign this issue to me under hacktoberfest.
<img width="960" alt="2022-10-17 (2)" src="https://user-images.githubusercontent.com/101176297/196230816-39c17391-5d46-45d8-8cb0-0ae7147324dc.png">

**Comment by flyingSaucer87** [comment]
Sure @Akshitha2106. Please fix this issue. It has been assigned to you

**Comment by Akshitha2106** [comment]
Respected Sir (@flyingSaucer87 ) please accept my PR under hacktoberfest I have done the changes according to the issue
