### ISSUE TITLE
building an aboutus.html

### ISSUE THREAD

**Issue by flyingSaucer87** [flyingSaucer87/community-website#27]
Every establishment has a page to tell viewers about themselves. Let's create a simple about us page for our establishment as well!

**Comment by lakshyaagr1105** [comment]
Hey @flyingSaucer87  , I am Lakshya i would love to work on this issue, so kindly assign this issue to me.

**Comment by Rohitsingh385** [comment]
hey can you assign me with this work? you can see my profile i'm pretty good with my work :)

**Comment by satyamrs00** [comment]
I can do it. You can see my profile to see samples . Can you assign it to me ?

**Comment by flyingSaucer87** [comment]
@lakshyaagr1105 You have been assigned this issue.
