### ISSUE TITLE
Menu button gets invisible/white when hovered upon

### ISSUE THREAD

**Issue by thisisamandang** [flyingSaucer87/community-website#270]
Hey @flyingSaucer87 , Please assign this issue to me under **Hacktober Fest**. 

![ss](https://user-images.githubusercontent.com/70525647/197294794-f79c8881-8fb9-4aad-a467-f50d2a85606c.PNG)

**Comment by manishyadav12** [comment]
I have made a PR regarding this issue.

**Comment by thisisamandang** [comment]
Okay, I didn't see it.
