### ISSUE TITLE
Home page repetiton

### ISSUE THREAD

**Issue by kalosFestus** [flyingSaucer87/community-website#295]
I feel like the Home button here is kind of repetitive and unnecessary, the logo points to the home page(index.html), the brand name Los Pollos Hermanos points to the home page as well (index.html) and then a home button, I feel the home button should be removed, thanks... I could work on it if approved and assigned.

![Home repetition](https://user-images.githubusercontent.com/79145625/198171252-ee4c2a5b-264e-4071-995e-ff705a70da1b.png)

**Comment by flyingSaucer87** [comment]
Please do the needful changes. This issue has been assigned to you @kalosFestus

**Comment by kalosFestus** [comment]
Thank you @flyingSaucer87, please accept my PR under hacktoberfest I have done the changes according to the issue.
