### ISSUE TITLE
Fix style.css

### ISSUE THREAD

**Issue by flyingSaucer87** [flyingSaucer87/community-website#31]
Some changes can be made to the css file

**Comment by Kesav890** [comment]
can i have this issue

**Comment by flyingSaucer87** [comment]
@Kesav890 for sure! I have assigned this issue to you.

**Comment by Kesav890** [comment]
can i know what kind of changes you need?

**Comment by flyingSaucer87** [comment]
@Kesav890 The text and images are not properly aligned. You can help in aligning them and changing the text styles a little

**Comment by Kesav890** [comment]
ok

**Comment by roshan2152** [comment]
Can you assign it to me? @flyingSaucer87

**Comment by Kesav890** [comment]
@flyingSaucer87 can you please unassign me ?

**Comment by roshan2152** [comment]
> @flyingSaucer87 can you please unassign me ?

U can unassign yourself.

**Comment by Kesav890** [comment]
How?

**Comment by flyingSaucer87** [comment]
@Kesav890 You have been unassigned from this issue. @roshan2152 You can go ahead with it.

**Comment by roshan2152** [comment]
Hey, @flyingSaucer87 can you exactly tell me what you need int the website?
