### ISSUE TITLE
Add aboutus.css

### ISSUE THREAD

**Issue by flyingSaucer87** [flyingSaucer87/community-website#34]
The about us page could have some fixing and alignments with css

**Comment by abhijeet8800** [comment]
I would like to work on this issue @flyingSaucer87. Can you please assign it to me.

**Comment by Anurag-Singh-04** [comment]
Hey @flyingSaucer87 I would like to work on this issue. Can you please assign it to me.

**Comment by flyingSaucer87** [comment]
@abhijeet8800  Even though this issue has been contributed to, you can add some changes you think would be useful. I have assigned this issue to you.

**Comment by abhijeet8800** [comment]
Can you please provide me the link to your website.

**Comment by flyingSaucer87** [comment]
@abhijeet8800 The website is not published yet. We intend to publish it after hacktoberfest ends.
