### ISSUE TITLE
menu.html needs improvement

### ISSUE THREAD

**Issue by DiscoPanzer** [flyingSaucer87/community-website#36]
The menu.html file looks bland. It could be improved

**Comment by sunidhisachan** [comment]
hey @DiscoPanzer I can try this. Can you assign this to me?

**Comment by flyingSaucer87** [comment]
@sunidhisachan sure. You have been assigned this issue!

**Comment by deepanshu-sharmaa** [comment]
Hello @flyingSaucer87 can you please assign me this issue
