### ISSUE TITLE
Fix aboutus.css

### ISSUE THREAD

**Issue by KislayMishra69** [flyingSaucer87/community-website#43]
I feel like aboutus.css needs some changes. It can be defined a little more

**Comment by burhanharoon** [comment]
Can you explain a bit more? And please assign this to me. Thanks!

**Comment by Purva2803** [comment]
I will do the changes in CSS according to the need please assign me this issue.

**Comment by KaustubhMishra69** [comment]
@burhanharoon I think instead of standard lorem ipsum text, a legitimate-looking about us page would look better. Some fixes in the text alignments and styles can also be made. 
![image](https://user-images.githubusercontent.com/78745590/194228297-4db6be19-2ec4-4218-b2bb-944a05db3df0.png)

**Comment by flyingSaucer87** [comment]
@burhanharoon You can help with the html file and the texts. @Purva2803 You can do the changes in the CSS files. You both are assigned this issue. Good luck!

**Comment by burhanharoon** [comment]
Ok. I'm on it!

**Comment by Purva2803** [comment]
okay, I am happy to do that.
