### ISSUE TITLE
Improve contact section

### ISSUE THREAD

**Issue by kushum-sonali** [flyingSaucer87/community-website#45]
there is no send button in contact section 
![image](https://user-images.githubusercontent.com/97432957/194236464-a55dccd6-31b8-4ef5-a7b2-45e18b8316b5.png)
 css is also not looking good 
 can u assign me this issue @flyingSaucer87

**Comment by flyingSaucer87** [comment]
Sure. @kushum-sonali you are assigned this issue. Good luck!
