### ISSUE TITLE
HTML is not semantic.

### ISSUE THREAD

**Issue by Samadeen** [flyingSaucer87/community-website#48]
A header should be holding the nav bar and the page content should be in a main element.

**Comment by PratikDey** [comment]
Can I contribute to this issue?

**Comment by NajeebaNasir** [comment]
Hi, @flyingSaucer87   I am Najeeba(front-end developer) and I would like to work on this issue.

**Comment by EnechukwuChibuike** [comment]
Let me work on this.

**Comment by flyingSaucer87** [comment]
@NajeebaNasir you can go ahead with this issue. Good luck!

**Comment by Samadeen** [comment]
I created the issue... It's only fair I get assigned to it.
