### ISSUE TITLE
improve landing page design

### ISSUE THREAD

**Issue by abhishek12raj** [flyingSaucer87/community-website#49]
landing page design is not proper 
![image](https://user-images.githubusercontent.com/99470924/194263961-8b5e112a-5403-4c04-af1f-743359b78d7b.png)
can u assign me this issue @flyingSaucer87

**Comment by flyingSaucer87** [comment]
Sure. You can work on this issue @abhishek12raj

**Comment by GargDivanshu** [comment]
Hey can I work on this issue?

**Comment by jyotika6221** [comment]
Please assign me this issue.
