### ISSUE TITLE
Fix header and footer 

### ISSUE THREAD

**Issue by ARPITJ0SHI** [flyingSaucer87/community-website#50]
I feel like (aboutus.html) needs some changes.
The header is not properly aligned and needs some fixes over the search bar and fix social icons in the footer and basic typography errors
Please assign me this issue.

**Comment by flyingSaucer87** [comment]
Sure. Please go ahead with the issue @ARPITJ0SHI

**Comment by Murtaza-Farooqui** [comment]
I would like to add footer to main page
please assign it to me
