### ISSUE TITLE
Menu Page

### ISSUE THREAD

**Issue by KanjiZain** [flyingSaucer87/community-website#55]
Will Create a Better UI for Menu Page

**Comment by flyingSaucer87** [comment]
Sure. Issue has been assigned to you @KanjiZain

**Comment by amansingh1373** [comment]
@flyingSaucer87 i think i can improve the UI kindly assign me this task

**Comment by amansingh1373** [comment]
@flyingSaucer87 i have a doubt can i make a new css file for menu page and also add new classes removing the old one's i think you have made a universal CSS classes for every page but it would be hard for me to use your classes as i dont have and idea what all classes are there(documentation is not there)
