### ISSUE TITLE
Readme needs some improvements.

### ISSUE THREAD

**Issue by AnandSY** [flyingSaucer87/community-website#62]
I feel like readme file needs some changes.
I can do that please assign this to me under hacktoberfest.

**Comment by flyingSaucer87** [comment]
Hey @AnandSY. Can you explain what kind of changes you want to do?

**Comment by AnandSY** [comment]
1. I will center the project heading and make the objective bold.
2. Steps to contribute (a guide for forking and making Pull requests)
3. Add contributors to bottom of readme

I basically want to do these kind of changes.

**Comment by flyingSaucer87** [comment]
Sounds good. You can go ahead with the changes
