### ISSUE TITLE
making index.html more readable

### ISSUE THREAD

**Issue by RIKI-05** [flyingSaucer87/community-website#64]
@FlyingSaucer87 I feel like (index.html) needs some comments to improve the readability. Also, there is some typo can I work on it?

**Comment by koder-aritra** [comment]
@flyingSaucer87 can you assign this issue to me?

**Comment by flyingSaucer87** [comment]
@RIKI-05 Sure! You have been assigned this issue

**Comment by RIKI-05** [comment]
> @RIKI-05 Sure! You have been assigned this issue
Thanks, @flyingSaucer87  have created the Pull request

**Comment by kalaSriSaiRaksha** [comment]
I'll resolve this issue
