### ISSUE TITLE
Hero section needs improvement

### ISSUE THREAD

**Issue by chandannkrp** [flyingSaucer87/community-website#75]
Hey @flyingSaucer87, I noticed the hero section of the website needs some improvement.
I think i can make it more appealing.

**Comment by flyingSaucer87** [comment]
Hey @ChandanP007. Which section are you referring to as the 'Hero' section? Can you send me an SS of it?

**Comment by chandannkrp** [comment]
![image](https://user-images.githubusercontent.com/95927947/194363866-09ff4a59-737d-4c3d-a8fe-d788b44b5cdb.png)
@flyingSaucer87

**Comment by chandannkrp** [comment]
main section below the navigation

**Comment by flyingSaucer87** [comment]
@ChandanP007 This issue has already been worked on, and now been fixed. So there is no need to do further changes. Thank you for your concerns
