### ISSUE TITLE
About us page looks bland. We can add some more styles and designs to it

### ISSUE THREAD

**Issue by UltigendLemate** [flyingSaucer87/community-website#79]
We can design the about us page better than this. We can have a founder pic on right and text on left in the first section. in the second section, below the heading "why choose us" we can have 5-6 squares (3x2 grid) . each square will have a point written on it along with some graphic image. Please assign this to me. I d love to work on this page. I have more ideas too

**Comment by flyingSaucer87** [comment]
That's a great thought @UltigendLemate. Please go ahead with your desired changes. I have assigned this issue to you

**Comment by UltigendLemate** [comment]
DId a PR. @flyingSaucer87 check.

**Comment by flyingSaucer87** [comment]
Will look into it
