### ISSUE TITLE
Fix overlapping text

### ISSUE THREAD

**Issue by KislayMishra69** [flyingSaucer87/community-website#80]
The text in index.html file is overlapping the image. 
![image](https://user-images.githubusercontent.com/78745590/194368149-8db47a2b-9fe1-409c-9ce4-f37c022ca1bf.png)

**Comment by ProtyayMnd50** [comment]
can you assign me this @KislayMishra69 pls?

**Comment by flyingSaucer87** [comment]
@ProtyayMnd50 You are assigned this issue. All the best!

**Comment by sumitbaroniya** [comment]
Please assign me this issue
