### ISSUE TITLE
DRY up the 'style.css' file

### ISSUE THREAD

**Issue by gcsandesh** [flyingSaucer87/community-website#82]
I feel like styles.css needs some changes.

In the styles.css file, the same code has been repeated more than one time and somewhere the code at the beginning of the file have been overwritten in the latter part of the file.

I would like to work on this for hacktoberfest. Assign it to me.

**Comment by flyingSaucer87** [comment]
For sure. @SandeshGC you have been assigned this issue. Good luck!
