### ISSUE TITLE
The Subscribe Button in aboutus.html can be modified

### ISSUE THREAD

**Issue by Shivyoddha** [flyingSaucer87/community-website#95]
I feel like (aboutus.html) needs some changes.
The subscribe button and the input can be modified to look better.

**Comment by Shivyoddha** [comment]
Please assign this issue to me

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by flyingSaucer87** [comment]
@Shivyoddha Please go ahead with the issue
